#!/usr/bin/env bash
# Transfer a file from local host to the remote server
# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
if [ "$#" -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit
fi
scp -o IdentityFile="$4" "$1" "$3"@"$2":~/
