#!/usr/bin/env bash
# Install and configure nginx on the server
sudo apt-get -y update
sudo apt-get -y install nginx
chown -R $USER:$USER /var/www/html/
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
