#!/usr/bin/env bash
# Display "To infinity and beyond" and Handle SEGTERM, SIGQUIT
# and SIGINT signal
echo "$$" > /var/run/myscript.pid
while (true)
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command"' SIGTERM
	trap 'rm /var/run/myscript.pid && exit' SIGTERM SIGQUIT
	trap 'echo "Y U no love me?!"' SIGINT
done
