#!/usr/bin/env bash
# Loop from 1 to 100 and display each number
# display "FizzBuzz" when the number is a multiple of 3 and 5
# displays "Fizz" when the number is a multiple of 3
# displays "Buzz" when the number is a multiple of 5
IFS=:
input="/etc/passwd"
while read -r f1 f2 f3 f4 f5 f6 f7
do
	echo "The user $f1 is part of the $f4 gang, lives in $f6 and rides $f7.$f3's place is protected by the passcode $f2,more info about the user here: $f5"
done < "$input"
