#!/usr/bin/env bash
# Loop from 1 to 100 and display each number
# display "FizzBuzz" when the number is a multiple of 3 and 5
# displays "Fizz" when the number is a multiple of 3
# displays "Buzz" when the number is a multiple of 5
IFS=:
input="/etc/passwd"
while read -r username password uid guid info home shell
do
	echo -n "The user $username is part of the $guid gang, "
	echo -n "lives in $home and rides $shell. "
	echo -n "$uid's place is protected by the passcode $password, "
	echo "more info about the user here: $info"
done < "$input"
